# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53c8988804cc4e8c016a092b188a241a51c0cc13461d5a3b7bae96a424ed2346d44527b8a10eaf2d707188c51f244561aa7c601256cf0e9f6977b2d08baa86c0

test:
  secret_key_base: 5f1ef540a8f37d2bfea11ed04033e514c71463a881b508c86bfd3615fff28abc045c287984beacc782b826b6bc6443d289d1f2ee02eaa29584e42d43f62d3200

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
